/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Shop, Product, Order, Review, Coupon, AppState } from './types';

export const INITIAL_SHOPS: Shop[] = [
  {
    id: 'shop-1',
    name: 'Sourdough & Co.',
    description: 'Artisanal micro-bakery specializing in 48-hour naturally fermented wild yeast breads, croissants, and seasonal fruit tarts.',
    rating: 4.9,
    reviewCount: 142,
    logo: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=150',
    banner: 'https://images.unsplash.com/photo-1517433456452-f9633a875f6f?auto=format&fit=crop&q=80&w=1200',
    category: 'Bakery',
    distance: '0.4 miles',
    deliveryTime: '20-30 min',
    minimumOrder: 10,
    address: '412 Maple Street, Greenpoint',
    verified: true,
    approved: true,
    ownerName: 'Clara Jenkins',
    ownerEmail: 'clara@sourdoughco.com',
    phone: '(555) 321-4820',
    revenue: 4850.00,
    joinedDate: '2025-03-12',
  },
  {
    id: 'shop-2',
    name: 'GreenLife Organics',
    description: 'Sustainably farmed, certified organic fruits, vegetables, and fresh herbs sourced daily from regional family farms.',
    rating: 4.8,
    reviewCount: 98,
    logo: 'https://images.unsplash.com/photo-1574316071802-0d684efa7bf5?auto=format&fit=crop&q=80&w=150',
    banner: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&q=80&w=1200',
    category: 'Produce',
    distance: '0.8 miles',
    deliveryTime: '25-40 min',
    minimumOrder: 15,
    address: '782 Orchard Avenue, East River',
    verified: true,
    approved: true,
    ownerName: 'Marcus Solis',
    ownerEmail: 'marcus@greenlife.com',
    phone: '(555) 762-9810',
    revenue: 8210.50,
    joinedDate: '2025-01-15',
  },
  {
    id: 'shop-3',
    name: 'The Daily Grind',
    description: 'Single-origin beans hand-roasted in small batches. Hot brews, cold brews, and premium home-brewing equipment.',
    rating: 4.7,
    reviewCount: 215,
    logo: 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&q=80&w=150',
    banner: 'https://images.unsplash.com/photo-1498804103079-a6351b050096?auto=format&fit=crop&q=80&w=1200',
    category: 'Coffee',
    distance: '1.2 miles',
    deliveryTime: '15-25 min',
    minimumOrder: 8,
    address: '109 Roasting Lane, Warehouse District',
    verified: true,
    approved: true,
    ownerName: 'Nico Sterling',
    ownerEmail: 'nico@thedailygrind.co',
    phone: '(555) 893-1024',
    revenue: 6120.25,
    joinedDate: '2025-02-18',
  },
  {
    id: 'shop-4',
    name: 'Flora & Clay',
    description: 'Curated wellness boutique offering organic soy-wax candles, hand-thrown pottery, and seasonal botanical arrangements.',
    rating: 4.9,
    reviewCount: 54,
    logo: 'https://images.unsplash.com/photo-1526047932273-341f2a7631f9?auto=format&fit=crop&q=80&w=150',
    banner: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&q=80&w=1200',
    category: 'Artisan Crafts',
    distance: '1.5 miles',
    deliveryTime: '30-45 min',
    minimumOrder: 20,
    address: '22 Artisan Way, Cobble Hill',
    verified: true,
    approved: true,
    ownerName: 'Aveline Moreau',
    ownerEmail: 'aveline@floraclay.com',
    phone: '(555) 451-9988',
    revenue: 3410.00,
    joinedDate: '2025-05-04',
  },
  {
    id: 'shop-5',
    name: 'The Pantry Guild',
    description: 'Fine specialty pantry provisions. Hand-pressed olive oils, aged vinegars, rare spices, and raw regional honeys.',
    rating: 4.6,
    reviewCount: 39,
    logo: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&q=80&w=150',
    banner: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&q=80&w=1200',
    category: 'Pantry',
    distance: '2.1 miles',
    deliveryTime: '35-50 min',
    minimumOrder: 25,
    address: '67 Larder Court, Heights West',
    verified: false,
    approved: false,
    ownerName: 'Silas Vance',
    ownerEmail: 'silas@pantryguild.com',
    phone: '(555) 234-8761',
    revenue: 0.00,
    joinedDate: '2026-07-15',
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  // Shop 1 - Sourdough & Co. (Bakery)
  {
    id: 'prod-101',
    shopId: 'shop-1',
    shopName: 'Sourdough & Co.',
    name: 'Classic Country Sourdough Batard',
    description: 'Our signature loaf. Made with stone-ground heirloom grains, 48-hour slow cold fermentation for a deep, complex flavor and a thick, blistered caramelized crust.',
    price: 8.50,
    rating: 4.9,
    reviewCount: 78,
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=600',
    category: 'Bakery',
    inventory: 15,
    salesCount: 420,
    tags: ['Sourdough', 'Fresh Baked', 'Vegan'],
    isTrending: true,
    isFeatured: true,
    deliveryTime: '20-30 min',
  },
  {
    id: 'prod-102',
    shopId: 'shop-1',
    shopName: 'Sourdough & Co.',
    name: 'Flaky Madagascar Vanilla Bean Croissant',
    description: 'Perfectly layered French style pastry utilizing 84% butterfat Normandy butter and a pure Madagascar vanilla sugar glaze. Exquisite crunch and tender crumb.',
    price: 4.75,
    originalPrice: 5.50,
    rating: 4.8,
    reviewCount: 45,
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&q=80&w=600',
    category: 'Bakery',
    inventory: 24,
    salesCount: 310,
    tags: ['Croissant', 'Pastry', 'Sweet'],
    isTrending: true,
    deliveryTime: '20-30 min',
  },
  {
    id: 'prod-103',
    shopId: 'shop-1',
    shopName: 'Sourdough & Co.',
    name: 'Meyer Lemon & Pistachio Tart',
    description: 'Sweet, buttery shortbread crust filled with tangy organic Meyer lemon curd, finished with roasted Sicilian pistachios and edible cornflowers.',
    price: 6.50,
    rating: 4.7,
    reviewCount: 19,
    image: 'https://images.unsplash.com/photo-1519869325930-281384150729?auto=format&fit=crop&q=80&w=600',
    category: 'Bakery',
    inventory: 8,
    salesCount: 85,
    tags: ['Tart', 'Dessert', 'Citrus'],
    deliveryTime: '20-30 min',
  },

  // Shop 2 - GreenLife Organics (Produce)
  {
    id: 'prod-201',
    shopId: 'shop-2',
    shopName: 'GreenLife Organics',
    name: 'Heritage Rainbow Tomatoes (1lb)',
    description: 'A beautiful medley of vintage organic tomato varieties, picked at absolute peak ripeness. Intense sweet-tart profile perfect for summer salads.',
    price: 6.99,
    originalPrice: 8.50,
    rating: 4.9,
    reviewCount: 52,
    image: 'https://images.unsplash.com/photo-1595855759920-86582396756a?auto=format&fit=crop&q=80&w=600',
    category: 'Produce',
    inventory: 35,
    salesCount: 240,
    tags: ['Organic', 'Heirloom', 'Fresh Picked'],
    isTrending: true,
    isFeatured: true,
    deliveryTime: '25-40 min',
  },
  {
    id: 'prod-202',
    shopId: 'shop-2',
    shopName: 'GreenLife Organics',
    name: 'Premium Pasture-Raised Blue Eggs (Dozen)',
    description: 'Laid by certified free-range Ameraucana hens fed an organic vegetarian diet. Highly nutritious with deep golden, rich yolks.',
    price: 9.25,
    rating: 4.8,
    reviewCount: 36,
    image: 'https://images.unsplash.com/photo-1516448620398-c5f44bf9f441?auto=format&fit=crop&q=80&w=600',
    category: 'Produce',
    inventory: 12,
    salesCount: 180,
    tags: ['Pasture Raised', 'Eggs', 'Organic'],
    isFeatured: true,
    deliveryTime: '25-40 min',
  },
  {
    id: 'prod-203',
    shopId: 'shop-2',
    shopName: 'GreenLife Organics',
    name: 'Fresh Hydroponic Sweet Basil Bunch',
    description: 'Aromatic large-leaf Italian sweet basil, harvested with roots intact to preserve absolute kitchen freshness and flavor intensity.',
    price: 3.50,
    rating: 4.6,
    reviewCount: 10,
    image: 'https://images.unsplash.com/photo-1618228479323-8cfb183669be?auto=format&fit=crop&q=80&w=600',
    category: 'Produce',
    inventory: 50,
    salesCount: 95,
    tags: ['Herbs', 'Local', 'Hydroponic'],
    deliveryTime: '25-40 min',
  },

  // Shop 3 - The Daily Grind (Coffee)
  {
    id: 'prod-301',
    shopId: 'shop-3',
    shopName: 'The Daily Grind',
    name: 'Cold-Brew Concentrate Bottle (32oz)',
    description: '16-hour cold extraction of sweet Ethiopian Yirgacheffe beans. Delivers crisp, refreshing notes of wild blueberry, bergamot, and a dark cocoa finish.',
    price: 14.00,
    rating: 4.8,
    reviewCount: 104,
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=600',
    category: 'Coffee',
    inventory: 20,
    salesCount: 410,
    tags: ['Cold Brew', 'Ethiopian', 'Concentrate'],
    isTrending: true,
    isFeatured: true,
    deliveryTime: '15-25 min',
  },
  {
    id: 'prod-302',
    shopId: 'shop-3',
    shopName: 'The Daily Grind',
    name: 'Guatemala Huehuetenango Coffee Beans (12oz)',
    description: 'Whole bean medium roast profile with magnificent tasting notes of stone fruit, creamy milk chocolate, and an elegant floral acidity. Roasted weekly.',
    price: 18.50,
    originalPrice: 21.00,
    rating: 4.7,
    reviewCount: 71,
    image: 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&q=80&w=600',
    category: 'Coffee',
    inventory: 40,
    salesCount: 220,
    tags: ['Whole Bean', 'Single Origin', 'Medium Roast'],
    deliveryTime: '15-25 min',
  },

  // Shop 4 - Flora & Clay (Artisan Crafts)
  {
    id: 'prod-401',
    shopId: 'shop-4',
    shopName: 'Flora & Clay',
    name: 'Wild Lavender & Bergamot Soy Candle',
    description: 'Hand-poured 100% natural US soy wax blended with pure organic lavender and Sicilian bergamot essential oils. 45-hour clean burn time in custom ceramic vessel.',
    price: 24.00,
    rating: 4.9,
    reviewCount: 32,
    image: 'https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&q=80&w=600',
    category: 'Artisan Crafts',
    inventory: 10,
    salesCount: 150,
    tags: ['Soy Candle', 'Essential Oils', 'Handcrafted'],
    isFeatured: true,
    deliveryTime: '30-45 min',
  },
  {
    id: 'prod-402',
    shopId: 'shop-4',
    shopName: 'Flora & Clay',
    name: 'Hand-Thrown Ceramic Coffee Mug',
    description: 'Elegant speckled clay breakfast mug finished in an organic, dripping light sage matte glaze. Each piece is individually crafted on the wheel.',
    price: 28.00,
    rating: 4.8,
    reviewCount: 22,
    image: 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&q=80&w=600',
    category: 'Artisan Crafts',
    inventory: 6,
    salesCount: 88,
    tags: ['Ceramic', 'Pottery', 'Wheel Thrown'],
    isTrending: true,
    deliveryTime: '30-45 min',
  },

  // Shop 5 - The Pantry Guild (Pantry - starts pending)
  {
    id: 'prod-501',
    shopId: 'shop-5',
    shopName: 'The Pantry Guild',
    name: 'Wild Meadow Raw Honey (12oz)',
    description: 'Raw, unpasteurized honey harvested from organic mountain meadows. Delightfully golden with rich notes of wild clover, thyme, and dandelion.',
    price: 16.50,
    rating: 4.6,
    reviewCount: 15,
    image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&q=80&w=600',
    category: 'Pantry',
    inventory: 15,
    salesCount: 0,
    tags: ['Raw Honey', 'Unpasteurized', 'Pantry'],
    deliveryTime: '35-50 min',
  }
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    shopId: 'shop-1',
    productId: 'prod-101',
    productName: 'Classic Country Sourdough Batard',
    author: 'Eleanor Vance',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=100',
    rating: 5,
    comment: 'The crust on this sourdough is absolutely magical, perfectly blistered and caramelized. Deep, sophisticated flavor that makes standard supermarket bread taste like cardboard!',
    date: '2026-07-18',
  },
  {
    id: 'rev-2',
    shopId: 'shop-1',
    productId: 'prod-102',
    productName: 'Flaky Madagascar Vanilla Bean Croissant',
    author: 'Julian Thorne',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=100',
    rating: 5,
    comment: 'Reminds me exactly of the bakeries in Paris. Incredible buttery lamination, flaky outer crunch, and that soft, airy interior. Worth every single cent.',
    date: '2026-07-15',
  },
  {
    id: 'rev-3',
    shopId: 'shop-2',
    productId: 'prod-201',
    productName: 'Heritage Rainbow Tomatoes',
    author: 'Sarah Jenkins',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&q=80&w=100',
    rating: 5,
    comment: 'Unbelievably sweet, and beautiful color variety. These heirloom tomatoes taste exactly like summer! Dressed simply with some high-quality olive oil and sea salt, it’s paradise.',
    date: '2026-07-20',
  }
];

export const INITIAL_COUPONS: Coupon[] = [
  {
    id: 'coup-1',
    code: 'NEIGHBOR10',
    discountPercent: 10,
    description: 'Get 10% off on your first order from any local neighborhood store.',
    minSpend: 15,
    active: true,
    expiryDate: '2026-12-31',
  },
  {
    id: 'coup-2',
    code: 'FRESHBAKE5',
    discountPercent: 5,
    description: 'Enjoy $5 off fresh bakery items of $20 or more.',
    minSpend: 20,
    active: true,
    expiryDate: '2026-11-30',
  },
  {
    id: 'coup-3',
    code: 'NEARMARTVIP',
    discountPercent: 15,
    description: '15% exclusive platform launch coupon for founding local customers.',
    minSpend: 30,
    active: true,
    expiryDate: '2026-08-31',
  }
];

export const INITIAL_ORDERS: Order[] = [];

export const INITIAL_STATE: AppState = {
  role: 'customer',
  shops: INITIAL_SHOPS,
  products: INITIAL_PRODUCTS,
  orders: INITIAL_ORDERS,
  reviews: INITIAL_REVIEWS,
  coupons: INITIAL_COUPONS,
  users: [],
  notifications: [],
  cart: [],
  wishlist: [],
  activeCouponCode: null,
  selectedLocation: 'Gulberg III, Lahore',
  selectedCategory: 'All',
  searchQuery: '',
  activeOrderTrackId: null,
  userProfile: {
    name: 'NearMart Patron',
    email: '',
    phone: '',
    address: '',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=150',
  },
  ownerStoreId: 'shop-1',
  chatSessions: {}
};
